---
  - hosts: aws_cassandra_cluster
    become: yes
    remote_user: ubuntu
    tasks:  
      - name: add cassandra gpg key to apt
        ansible.builtin.apt_key:
          url: https://www.apache.org/dist/cassandra/KEYS
          state: present
      
      - name: add cassandra repo tp apt
        ansible.builtin.apt_repository:
          repo: deb http://www.apache.org/dist/cassandra/debian 40x main
          state: present
          filename: cassandra
       
      - name: install cassandra
        apt:
          name: cassandra
          state: present    
      
      - name: remove cassandra.yaml file
        file:
          state: absent
          path: /etc/cassandra/cassandra.yaml 
      
      - name: copy the cassandra.yaml file
        copy:
          src: ./cassandra.yaml
          dest: /etc/cassandra/cassandra.yaml

      - name: restart cassandra service
        ansible.builtin.service:
          name: cassandra
          state: restarted
        
    