---
  - hosts: aws_cassandra_cluster
    become: yes
    remote_user: ubuntu
    tasks:  
      - name: add cassandra gpg key to apt
        apt_key:
          url: https://www.apache.org/dist/cassandra/KEYS
          state: present
      
      - name: add cassandra repo tp apt
        apt_repository:
          repo: deb http://www.apache.org/dist/cassandra/debian 40x main
          state: present
          filename: cassandra
       
      - name: install cassandra
        apt:
          name: cassandra
          state: present    
      
      - name: remove cassandra.yaml file
        file:
          state: absent
          path: /etc/cassandra/cassandra.yaml

      - name: copy cassandra.yaml
        copy: 
          src: ./cassandra.yaml
          dest: /etc/cassandra/cassandra.yaml  

      - name: raplace LOCALHOST on cassandra.yaml file
        replace: 
        path: /etc/cassandra/cassandra.yaml
        regexp: LOCALHOST
        replace: "{{ ansible_facts.eth0.ipv4.address }}"

      - name: restart cassandra service
        service:
          name: cassandra
          state: restarted          
